export { GenuiChat } from '../chat-v2/index.js';
export type { GenuiConversationHandle, ImportConversationItem } from '../chat-v2/useGenuiConversation.js';
export type { IMessageManagerBridge } from './chat.types.js';
export { useBubbleRoleAfterSlot } from '../chat-v2/composables/useBubbleRoleAfterSlot.js';
export * from './chat.types.js';
export * from './injection-tokens.js';
export * from './i18n/index.js';
export * from './event-emitter.js';
export * from './chat-utils.js';
export * from './think-tag-wrap-pattern.js';
