export const THEME_PREVIEW_COLOR_PRESETS = {
  light: {
    previewBorder: '#e6e6e6',
    previewBg: '#ffffff',
    sidebarBg: '#fafafa',
    mainBg: '#f5f5f5',
    skeletonBg: '#e6e6e6',
    newTaskBg: '#e6e6e6',
    bubbleBorder: '#e6e6e6',
    bubbleBg: 'transparent',
    senderBorder: '#d9d9d9',
    senderBg: '#ffffff',
  },
  lite: {
    previewBorder: '#d9e7f6',
    previewBg: '#ffffff',
    sidebarBg: '#ffffff',
    mainBg: '#f0f0f0',
    skeletonBg: '#d6e8ff',
    newTaskBg: '#e6e6e6',
    bubbleBorder: '#d6e8ff',
    bubbleBg: 'transparent',
    senderBorder: '#e5e5e5',
    senderBg: '#ffffff',
  },
  dark: {
    previewBorder: '#303030',
    previewBg: '#191919',
    sidebarBg: '#232323',
    mainBg: '#191919',
    skeletonBg: '#3a3a3a',
    newTaskBg: '#3a3a3a',
    bubbleBorder: '#3a3a3a',
    bubbleBg: 'transparent',
    senderBorder: '#333333',
    senderBg: '#191919',
  },
};
