packages:
  - packages/**/*
  - sites/**/*
  - docs
  - projects/**/*
  - '!packages/frameworks/vue/output/**'
  - '!packages/server/output/**'
  - '!packages/frameworks/angular/**/*'
  - '!projects/tiny-schema-renderer-ng/**/*'
