packages:
  - packages/**/*
  - sites/**/*
  - docs
  - projects/**/*
  - '!packages/frameworks/vue/output/**'
  - '!packages/server/output/**'
  - '!packages/frameworks/angular/**/*'
  - '!projects/tiny-schema-renderer-ng/**/*'
  - '!projects/*.worktrees'
  - '!projects/*.worktrees/**'

patchedDependencies:
  ai@6.0.116: patches/ai@6.0.116.patch
