import { type Type } from '@angular/core';
import {
  TiButtonComponent,
  TiButtonModule,
  TiCardComponent,
  TiCardHeaderComponent,
  TiCardModule,
  TiCheckboxComponent,
  TiCheckboxGroupComponent,
  TiCheckboxModule,
  TiDateComponent,
  TiDateModule,
  TiDateRangeComponent,
  TiDateRangeModule,
  TiFormfieldComponent,
  TiFormfieldModule,
  TiItemComponent,
  TiModalComponent,
  TiModalModule,
  TiPaginationComponent,
  TiPaginationModule,
  TiRadioComponent,
  TiRadioGroupComponent,
  TiRadioModule,
  TiRateComponent,
  TiRateModule,
  TiSelectComponent,
  TiSelectModule,
  TiSliderComponent,
  TiSliderModule,
  TiSwitchComponent,
  TiSwitchModule,
  TiTabComponent,
  TiTableComponent,
  TiTableModule,
  TiTabModule,
  TiTabsComponent,
  TiTextareaComponent,
  TiTextareaModule,
  TiTextComponent,
  TiTextModule,
  TiTipDirective,
  TiUploadComponent,
  TiUploadModule,
} from '@opentiny/ng';
import type { IRendererMaterials } from '../../../projects/renderer/src/renderer-materials';

(TiTextComponent['ɵcmp'] as any).selectors[0][0] = 'input';
(TiTextareaComponent['ɵcmp'] as any).selectors[0][0] = 'textarea';
(TiRadioComponent['ɵcmp'] as any).selectors[0][0] = 'input';
(TiCheckboxComponent['ɵcmp'] as any).selectors[0][0] = 'input';

const components: Record<string, Type<any>> = {
  TiButton: TiButtonComponent,
  TiSelect: TiSelectComponent,
  TiText: TiTextComponent,
  TiTable: TiTableComponent,
  TiModal: TiModalComponent,
  TiDate: TiDateComponent,
  TiPagination: TiPaginationComponent,
  TiTabs: TiTabsComponent,
  TiTab: TiTabComponent,
  TiCheckbox: TiCheckboxComponent,
  TiCheckboxGroup: TiCheckboxGroupComponent,
  TiRadio: TiRadioComponent,
  TiRadioGroup: TiRadioGroupComponent,
  TiSwitch: TiSwitchComponent,
  TiCard: TiCardComponent,
  TiUpload: TiUploadComponent,
  TiFormField: TiFormfieldComponent,
  TiCardHeader: TiCardHeaderComponent,
  TiItem: TiItemComponent,
  TiDateRange: TiDateRangeComponent,
  TiSlider: TiSliderComponent,
  TiRate: TiRateComponent,
  TiTextArea: TiTextareaComponent,
};

const modules: Record<string, Type<any>> = {
  TiButton: TiButtonModule,
  TiSelect: TiSelectModule,
  TiText: TiTextModule,
  TiTable: TiTableModule,
  TiModal: TiModalModule,
  TiDate: TiDateModule,
  TiPagination: TiPaginationModule,
  TiTabs: TiTabModule,
  TiTab: TiTabModule,
  TiCheckbox: TiCheckboxModule,
  TiCheckboxGroup: TiCheckboxModule,
  TiRadio: TiRadioModule,
  TiRadioGroup: TiRadioModule,
  TiSwitch: TiSwitchModule,
  TiCard: TiCardModule,
  TiUpload: TiUploadModule,
  TiFormField: TiFormfieldModule,
  TiCardHeader: TiCardModule,
  TiItem: TiFormfieldModule,
  TiDateRange: TiDateRangeModule,
  TiSlider: TiSliderModule,
  TiRate: TiRateModule,
  TiTextArea: TiTextareaModule,
};

const directives: Record<string, Type<any>> = {
  TiTip: TiTipDirective,
};

export const materials: IRendererMaterials = {
  components,
  modules,
  directives,
  autoApplyDirectives: {},
};
