import { Type } from '@angular/core';
import {
  TiButtonComponent,
  TiButtonModule,
  TiIconComponent,
  TiIconModule,
  TiSelectComponent,
  TiSelectModule,
  TiTextComponent,
  TiTextModule,
  TiTableComponent,
  TiTableModule,
  TiModalComponent,
  TiModalModule,
  TiDateComponent,
  TiDateModule,
  TiPaginationComponent,
  TiPaginationModule,
  TiTabsComponent,
  TiTabModule,
  TiCheckboxComponent,
  TiCheckboxModule,
  TiCheckboxGroupComponent,
  TiRadioComponent,
  TiRadioModule,
  TiRadioGroupComponent,
  TiTabComponent,
  TiSwitchComponent,
  TiSwitchModule,
  TiCardComponent,
  TiCardModule,
  TiUploadComponent,
  TiUploadModule,
  TiFormfieldComponent,
  TiFormfieldModule,
  TiCardHeaderComponent,
  TiItemComponent,
  TiDateRangeComponent,
  TiDateRangeModule,
  TiSliderComponent,
  TiSliderModule,
  TiRateComponent,
  TiRateModule,
  TiTextareaComponent,
  TiTextareaModule,
} from '@opentiny/ng';

(TiTextComponent['ɵcmp'] as any).selectors[0][0] = 'input';
(TiTextareaComponent['ɵcmp'] as any).selectors[0][0] = 'textarea';
(TiRadioComponent['ɵcmp'] as any).selectors[0][0] = 'input';
(TiCheckboxComponent['ɵcmp'] as any).selectors[0][0] = 'input';

export const components: Record<string, Type<any>> = {
  TiButton: TiButtonComponent,
  TiIcon: TiIconComponent,
  TiSelect: TiSelectComponent,
  TiText: TiTextComponent,
  TiTable: TiTableComponent,
  TiModal: TiModalComponent,
  TiDate: TiDateComponent,
  TiPagination: TiPaginationComponent,
  TiTabs: TiTabsComponent,
  TiTab: TiTabComponent,
  TiCheckbox: TiCheckboxComponent,
  TiCheckboxGroup: TiCheckboxGroupComponent,
  TiRadio: TiRadioComponent,
  TiRadioGroup: TiRadioGroupComponent,
  TiSwitch: TiSwitchComponent,
  TiCard: TiCardComponent,
  TiUpload: TiUploadComponent,
  TiFormField: TiFormfieldComponent,
  TiCardHeader: TiCardHeaderComponent,
  TiItem: TiItemComponent,
  TiDateRange: TiDateRangeComponent,
  TiSlider: TiSliderComponent,
  TiRate: TiRateComponent,
  TiTextArea: TiTextareaComponent,
};

export const modules: Record<string, Type<any>> = {
  TiButton: TiButtonModule,
  TiIcon: TiIconModule,
  TiSelect: TiSelectModule,
  TiText: TiTextModule,
  TiTable: TiTableModule,
  TiModal: TiModalModule,
  TiDate: TiDateModule,
  TiPagination: TiPaginationModule,
  TiTabs: TiTabModule,
  TiTab: TiTabModule,
  TiCheckbox: TiCheckboxModule,
  TiCheckboxGroup: TiCheckboxModule,
  TiRadio: TiRadioModule,
  TiRadioGroup: TiRadioModule,
  TiSwitch: TiSwitchModule,
  TiCard: TiCardModule,
  TiUpload: TiUploadModule,
  TiFormField: TiFormfieldModule,
  TiCardHeader: TiCardModule,
  TiItem: TiFormfieldModule,
  TiDateRange: TiDateRangeModule,
  TiSlider: TiSliderModule,
  TiRate: TiRateModule,
  TiTextArea: TiTextareaModule,
};
