export const moduleRefMap: Record<string, string> = {
  TiButton: 'TiButtonModule',
  TiSelect: 'TiSelectModule',
  TiText: 'TiTextModule',
  TiTable: 'TiTableModule',
  TiModal: 'TiModalModule',
  TiDate: 'TiDateModule',
  TiPagination: 'TiPaginationModule',
  TiTabs: 'TiTabModule',
  TiTab: 'TiTabModule',
  TiCheckbox: 'TiCheckboxModule',
  TiCheckboxGroup: 'TiCheckboxModule',
  TiRadio: 'TiRadioModule',
  TiRadioGroup: 'TiRadioModule',
  TiSwitch: 'TiSwitchModule',
  TiCard: 'TiCardModule',
  TiUpload: 'TiUploadModule',
  TiFormField: 'TiFormfieldModule',
  TiCardHeader: 'TiCardModule',
  TiItem: 'TiFormfieldModule',
  TiDateRange: 'TiDateRangeModule',
  TiSlider: 'TiSliderModule',
  TiRate: 'TiRateModule',
  TiTextArea: 'TiTextareaModule',
};

export const componentSelector: Record<string, string> = {
  TiButton: 'button',
  TiSelect: 'ti-select',
  TiText: 'input',
  TiTable: 'ti-table',
  TiModal: 'ti-modal',
  TiDate: 'ti-date',
  TiPagination: 'ti-pagination',
  TiTabs: 'ti-tabs',
  TiTab: 'ti-tab',
  TiCheckbox: 'input',
  TiCheckboxGroup: 'ti-checkbox-group',
  TiRadio: 'input',
  TiRadioGroup: 'ti-radio-group',
  TiSwitch: 'ti-switch',
  TiCard: 'ti-card',
  TiUpload: 'ti-upload',
  TiFormField: 'ti-formfield',
  TiCardHeader: 'ti-card-header',
  TiItem: 'ti-item',
  TiDateRange: 'ti-date-range',
  TiSlider: 'ti-slider',
  TiRate: 'ti-rate',
  TiTextArea: 'textarea',
};

export const componentExtraSelector: Record<string, string> = {
  TiButton: 'tiButton',
  TiText: 'tiText',
  TiTextArea: 'tiTextarea',
  TiRadio: 'tiRadio',
  TiCheckbox: 'tiCheckbox',
};
