export const miniWhiteList = [
  'a',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'p',
  'ol',
  'ul',
  'li',
  'div',
  'input',
  'video',
  'label',
  'Img',
  'Slot',
  'Text',
  'TinyIcon',
  'TinyForm',
  'TinyFormItem',
  'TinyButton',
  'TinyInput',
  'TinyRadio',
  'TinyRadioGroup',
  'TinySelect',
  'TinySwitch',
  'TinyNumeric',
  'TinyCheckbox',
  'TinyCheckboxButton',
  'TinyCheckboxGroup',
  'TinyDatePicker',
  'TinyGrid',
  'TinyCard',
];

export const standardWhiteList = [
  ...miniWhiteList,
  'TinyPager',
  'TinyHuichartsLine',
  'TinyHuichartsHistogram',
  'TinyHuichartsBar',
  'TinyHuichartsRadar',
  'TinyHuichartsRing',
  'TinyHuichartsPie',
  'TinyHuichartsFunnel',
  'TinyHuichartsScatter',
  'TinyHuichartsWaterfall',
  'TinyHuichartsGauge',
  'TinyHuichartsGraph',
  'TinyHuichartsProcess',
];

// TODO: plus物料和白名单袋完善
export const plusWhiteList = [
  ...standardWhiteList,
  'TinyCarouselItem',
  'TinyCarousel',
  'TinyTree',
  'TinyTransfer',
  // 'GridStack',
  // 'GridStackItem'
  // 'RouterView',
  // 'RouterLink',
  // 'Collection',
  // 'TinyBreadcrumb',
  // 'TinyBreadcrumbItem',
  // 'TinyCollapse',
  // 'TinyCollapseItem',
  // 'TinyTimeLine',
  // 'TinyTooltip',
  // 'TinyPopover',
  // 'TinyDialogBox',
  // 'TinyPopeditor',
];
