export const miniWhiteList = [
  'a',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'p',
  'ol',
  'ul',
  'li',
  'div',
  'img',
  'input',
  'video',
  'label',
  'Text',
  'TinyIcon',
  'TinyForm',
  'TinyFormItem',
  'TinyButton',
  'TinyInput',
  'TinyRadio',
  'TinyRadioGroup',
  'TinySelect',
  'TinySwitch',
  'TinyNumeric',
  'TinyCheckbox',
  'TinyCheckboxButton',
  'TinyCheckboxGroup',
  'TinyDatePicker',
  'TinyGrid',
  'TinyCard',
];

export const standardWhiteList = [
  ...miniWhiteList,
  'TinyTabs',
  'TinyTabItem',
  'TinyPager',
  'TinyHuichartsLine',
  'TinyHuichartsHistogram',
  'TinyHuichartsBar',
  'TinyHuichartsRadar',
  'TinyHuichartsRing',
  'TinyHuichartsPie',
  'TinyHuichartsFunnel',
  'TinyHuichartsScatter',
  'TinyHuichartsWaterfall',
  'TinyHuichartsGauge',
  'TinyHuichartsGraph',
  'TinyHuichartsProcess',
];

export const plusWhiteList = [
  ...standardWhiteList,
  // 面包屑组件会直接进行页面路由跳转，暂不开放
  // 'TinyBreadcrumb',
  // 'TinyBreadcrumbItem',
  'TinyAutocomplete',
  'TinyCascader',
  'TinyColorPicker',
  'TinyIpAddress',
  'TinySteps',
  'TinyCollapse',
  'TinyCollapseItem',
  'TinyTree',
  'TinyTransfer',
  'TinyPopeditor',
  'TinyCarousel',
  'TinyCarouselItem',
  'TinyDialogBox',
  'TinyTooltip',
  'TinyPopover',
];
