<template>
  <div class="app">
    <header class="app-header">
      <h1>GenUI Chat - 国际化示例</h1>
      <div class="header-actions">
        <select v-model="currentLocale" class="locale-select">
          <option value="zh_CN">简体中文</option>
          <option value="en_US">English</option>
        </select>
      </div>
    </header>

    <GenuiConfigProvider :locale="currentLocale" :i18n="customI18n" id="i18n-chat">
      <GenuiChat :url="url" model="deepseek-v3.2" :messages="messages" />
    </GenuiConfigProvider>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { GenuiConfigProvider, GenuiChat } from '@opentiny/genui-sdk-vue';
import type { I18nMessages } from '@opentiny/genui-sdk-vue';

const url = 'https://your-chat-backend/api';

const currentLocale = ref('en_US');

// 自定义国际化消息
const customI18n: I18nMessages = {
  zh_CN: {
    placeholder: {
      input: '请输入您的问题（已自定义）',
    },
    footer: {
      aiGenerated: '内容由AI生成，仅供参考（已自定义）',
    },
  },
  en_US: {
    placeholder: {
      input: 'Please enter your question (customized)',
    },
    footer: {
      aiGenerated: 'Content generated by AI, for reference only (customized)',
    },
  },
};


const messages = [
  {
    role: 'user',
    content: 'Hello, how are you?',
  },
  {
    role: 'assistant',
    content: 'I am doing well, thank you for asking!',
  },
];
</script>

<style scoped>
.app {
  display: flex;
  flex-direction: column;
  height: 460px;
}

.app-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px;
  border-bottom: 1px solid #eee;
}

.app-header h1 {
  margin: 0;
  font-size: 20px;
}

.locale-select {
  padding: 8px 12px;
  border: 1px solid #ddd;
  border-radius: 4px;
  background: white;
  cursor: pointer;
  font-size: 14px;
}

.locale-select:hover {
  background: #f5f5f5;
}
</style>
